//===-- AVRAsmPrinter.h - AVR LLVM assembly writer ----------*- C++ -*-===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file contains a printer that converts from our internal representation
// of machine-dependent LLVM code to AVR assembly language.
//
//===----------------------------------------------------------------------===//

#ifndef AVRASMPRINTER_H
#define AVRASMPRINTER_H

#include "AVR.h"
#include "AVRTargetMachine.h"
//#include "AVRDebugInfo.h"
#include "AVRMCAsmInfo.h"
//#include "AVRTargetObjectFile.h"
#include "llvm/Analysis/DebugInfo.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetMachine.h"
#include <list>
#include <string>

namespace llvm {
  class VISIBILITY_HIDDEN AVRAsmPrinter : public AsmPrinter {
  public:
    explicit AVRAsmPrinter(formatted_raw_ostream &O, TargetMachine &TM,
                             const MCAsmInfo *T, bool V);
  private:
    virtual const char *getPassName() const {
      return "AVR Assembly Printer";
    }
    void printInstruction(const MachineInstr *MI); // definition autogenerated.
    static const char *getRegisterName(unsigned RegNo);
    void printOperand(const MachineInstr *MI, int opNum);
    bool runOnMachineFunction(MachineFunction &F);
    
    /// PrintGlobalVariable - Emit the specified global variable and its
    /// initializer to the output stream.
    virtual void PrintGlobalVariable(const GlobalVariable *GV) {
      // AVR doesn't use normal hooks for this.
    }

 #if 0   
    AVRTargetObjectFile &getObjFileLowering() const {
      return (AVRTargetObjectFile &)AsmPrinter::getObjFileLowering();
    }

    bool runOnMachineFunction(MachineFunction &F);
    void printCCOperand(const MachineInstr *MI, int opNum);

    bool printMachineInstruction(const MachineInstr *MI);
    void EmitFunctionDecls (Module &M);
    void EmitUndefinedVars (Module &M);
    void EmitDefinedVars (Module &M);
    void EmitIData (Module &M);
    void EmitUData (Module &M);
    void EmitAllAutos (Module &M);
    void EmitRomData (Module &M);
    void EmitSharedUdata(Module &M);
    void EmitUserSections (Module &M);
    void EmitFunctionFrame(MachineFunction &MF);
    void printLibcallDecls();
    void EmitUninitializedDataSection(const AVRSection *S);
    void EmitInitializedDataSection(const AVRSection *S);
    void EmitSingleSection(const AVRSection *S);
    void EmitSectionList(Module &M, 
                         const std::vector< AVRSection *> &SList);
    void ColorAutoSection(const Function *F);
  protected:
    bool doInitialization(Module &M);
    bool doFinalization(Module &M);

    
  private:
    AVRTargetObjectFile *PTOF;
    AVRTargetLowering *PTLI;
    AVRDbgInfo DbgInfo;
    const AVRMCAsmInfo *PMAI;
    std::list<const char *> LibcallDecls; // List of extern decls.
    std::vector<const GlobalVariable *> ExternalVarDecls;
    std::vector<const GlobalVariable *> ExternalVarDefs;
#endif
  };
} // end of namespace

#endif
