//=====-- AVRSubtarget.h - Define Subtarget for the AVR ---*- C++ -*--====//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source 
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file declares the AVR specific subclass of TargetSubtarget.
//
//===----------------------------------------------------------------------===//

#ifndef AVRSUBTARGET_H
#define AVRSUBTARGET_H

#include "llvm/Target/TargetSubtarget.h"

#include <string>

namespace llvm {
class Module;

class AVRSubtarget : public TargetSubtarget {

  bool HasJMP;
  bool HasMUL;
  bool HasMOVW;
  bool HasJTAG;
  bool HasEIJMP;
  bool HasSPM;
  bool HasDES;

  bool IsAVR2;
  bool IsAVR25;
  bool IsAVR3;
  bool IsAVR31;
  bool IsAVR4;
  bool IsAVR5;
  bool IsAVR51;
  bool IsAVR6;
  bool IsXMEGA;
public:
  /// This constructor initializes the data members to match that
  /// of the specified module.
  ///
  AVRSubtarget(const Module &M, const std::string &FS);
  
  /// ParseSubtargetFeatures - Parses features string setting specified 
  /// subtarget options.  Definition of function is auto generated by tblgen.
  void ParseSubtargetFeatures(const std::string &FS, const std::string &CPU);
};
} // End llvm namespace

#endif  // AVRSUBTARGET_H
