//=====-- AVRSubtarget.h - Define Subtarget for the AVR ---*- C++ -*--====//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file declares the AVR specific subclass of TargetSubtarget.
//
//===----------------------------------------------------------------------===//

#ifndef AVRSUBTARGET_H
#define AVRSUBTARGET_H

#include "llvm/Target/TargetInstrItineraries.h"
#include "llvm/Target/TargetSubtarget.h"

#include <string>

namespace llvm {

class AVRSubtarget : public TargetSubtarget {

  bool HasJMP;
  bool HasMUL;
  bool HasMOVW;
  bool HasJTAG;
  bool HasEIJMP;
  bool HasSPM;
  bool HasDES;
  bool HasEIJMP_EICALL;
  bool HasELPM;
  bool HasELPMX;
  bool HasJMP_CALL;
  bool HasMOVW_LPMX;
  bool HasRAMPX_Y_D;
  bool HasTiny_Regs_Insns;  
  
  bool IsAsmOnly;
  bool IsAVRTINY1;
  bool IsAVRXMEGA1;
  bool IsAVRXMEGA2;
  bool IsAVRXMEGA3;
  bool IsAVRXMEGA4;
  bool IsAVRXMEGA5;
  bool IsAVRXMEGA6;
  bool IsAVRXMEGA7;

  bool IsAVR1;
  bool IsAVR2;
  bool IsAVR25;
  bool IsAVR3;
  bool IsAVR31;
  bool IsAVR35;
  bool IsAVR4;
  bool IsAVR5;
  bool IsAVR51;
  bool IsAVR6;
  bool IsXMEGA;
public:

  AVRSubtarget(const std::string &TT, const std::string &FS);

  /// ParseSubtargetFeatures - Parses features string setting specified
  /// subtarget options.  Definition of function is auto generated by tblgen.
  std::string ParseSubtargetFeatures(const std::string &FS, const std::string &CPU);
};
} // End llvm namespace

#endif  // AVRSUBTARGET_H
